### ISSUE TITLE
is there any documentetion for use

### ISSUE THREAD

**Issue by desaikalpesh34** [DenisOgr/yii2-google-adwords-helpers#11]

**Comment by caox2110** [comment]
Hi, please some documentation for use...

**Comment by desaikalpesh34** [comment]
Still no doc found...):

**Comment by DenisOgr** [comment]
Hi, guys.
Sorry, this  is not open source project, this public project in our company. 
And we sometime have not time to write docs. 
You can use it, but save links to original source and contribution.

Thanks, Denis.
