### ISSUE TITLE
Cannot clone by composer

### ISSUE THREAD

**Issue by dakiquang** [DenisOgr/yii2-google-adwords-helpers#2]
Hi @DenisOgr,

I tried to install your package by composer, but no luck. I get an error as:
![2014-12-29_17h57_45](https://cloud.githubusercontent.com/assets/1046250/5568101/86c0f5be-8f84-11e4-8d00-16d5b01f51b5.png)

**Comment by DenisOgr** [comment]
you need add repo to composer repositories.
it pack is not in packagist.org
